# Generated by Django on 2026-02-25 15:00

import django.db.models.deletion
from django.db import migrations, models

def backfill_order_position_event(apps, schema_editor):
    OrderPosition = apps.get_model('base', 'OrderPosition')
    # Use bulk update for efficiency if there are many records
    for op in OrderPosition.objects.select_related('order').all():
        if op.order:
            op.event = op.order.event
            op.save(update_fields=['event'])

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_submissiontype_position_cfp_default_type'),
    ]

    operations = [
        # 1. Add the field allowing nulls temporarily
        migrations.AddField(
            model_name='orderposition',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_positions', to='base.Event', verbose_name='Event'),
        ),
        
        # 2. Backfill the existing records
        migrations.RunPython(
            backfill_order_position_event,
            reverse_code=migrations.RunPython.noop
        ),
        
        # 3. Alter the event field to forbid nulls mapped correctly to existing schemas
        migrations.AlterField(
            model_name='orderposition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_positions', to='base.Event', verbose_name='Event'),
        ),
        
        # 4. Remove global uniqueness, maintain DB index.
        migrations.AlterField(
            model_name='orderposition',
            name='pseudonymization_id',
            field=models.CharField(max_length=16, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='secret',
            field=models.CharField(max_length=255, db_index=True),
        ),
        
        # 5. Attach native per-event scoping restrictions using Django constraints
        migrations.AddConstraint(
            model_name='orderposition',
            constraint=models.UniqueConstraint(fields=('event', 'pseudonymization_id'), name='orderposition_pseudo_id_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderposition',
            constraint=models.UniqueConstraint(fields=('event', 'secret'), name='orderposition_secret_event_unique'),
        ),
    ]
